services/ags: replace hyprctl-swallow with a bash script

diff --git a/homes/notashelf/services/shared/ags/js/scripts/move_window b/homes/notashelf/services/shared/ags/js/scripts/move_window
--- a/homes/notashelf/services/shared/ags/js/scripts/move_window
+++ b/homes/notashelf/services/shared/ags/js/scripts/move_window
@@ -1,13 +1,20 @@
 #!/usr/bin/env bash
-# Script by https://github.com/exoess
-
-if [ "$#" -ne 2 ]; then
-    echo "Usage: $0 <position> <size>"
-    exit 1
-fi
 
 move_window() {
-    hyprctl --batch "dispatch moveactive exact $(echo $1 | sed 's/,/ /'); dispatch resizeactive exact $(echo $2 | sed 's/x/ /')"
+	local position="$1"
+	local size="$2"
+
+	if [[ -z "$position" || -z "$size" ]]; then
+		echo "Error: Both position and size are required." 1>&2
+		exit 1
+	fi
+
+	hyprctl --batch "dispatch moveactive exact ${position//,/ }; dispatch resizeactive exact ${size//x/ }"
 }
+
+if [[ $# -ne 2 ]]; then
+	echo "Usage: $0 <position> <size>"
+	exit 1
+fi
 
 move_window "$1" "$2"
diff --git a/homes/notashelf/services/shared/ags/js/scripts/open_window b/homes/notashelf/services/shared/ags/js/scripts/open_window
--- a/homes/notashelf/services/shared/ags/js/scripts/open_window
+++ b/homes/notashelf/services/shared/ags/js/scripts/open_window
@@ -1,13 +1,22 @@
 #!/usr/bin/env bash
-# Script by https://github.com/exoess
-
-if [ "$#" -ne 3 ]; then
-    echo "Usage: $0 <position> <size>"
-    exit 1
-fi
 
 open_window() {
-    hyprctl dispatch exec "[float; move $(echo $1 | sed 's/,/ /'); size $(echo $2 | sed 's/x/ /')] $3"
+	local position="$1"
+	local size="$2"
+	local command="$3"
+
+	# Validate input
+	if [[ -z "$position" || -z "$size" || -z "$command" ]]; then
+		echo "Error: Position, size, and command are required." 1>&2
+		exit 1
+	fi
+
+	hyprctl dispatch exec "[float; move ${position//,/ }; size ${size//x/ }] $command"
 }
+
+if [[ $# -ne 3 ]]; then
+	echo "Usage: $0 <position> <size> <command>"
+	exit 1
+fi
 
 open_window "$1" "$2" "$3"
